services:
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./databases:/app/databases
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./tests:/app/tests
    env_file:
      - .env
