services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Data persistence
      - ./databases:/app/databases
      - ./vector_store:/app/vector_store
      - ./assets:/app/assets:ro
      - ./models:/app/models:ro
      - ./sample_data:/app/sample_data:ro
    develop:
      watch:
        # Sync all our source code changes instantly
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests
        - action: sync
          path: ./scripts
          target: /app/scripts
        - action: sync
          path: ./alembic
          target: /app/alembic
        - action: sync
          path: ./alembic.ini
          target: /app/alembic.ini


        # Rebuild the image automatically if dependencies change
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
    restart: unless-stopped
    networks:
        - provai_net

  tailwind_watcher:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      target: frontend_builder
    command: npm run watch:css
    tty: true
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./tailwind.config.js
    restart: unless-stopped
    networks:
      - provai_net

networks:
  provai_net:
    driver: bridge
