[tox]
env_list = check, test
min_version = 4.0
requires = tox-uv

[testenv]
basepython = python3.13

[testenv:check]
runner = uv-venv-lock-runner
extras = quality
commands =
	ruff check .
	ruff format --check .
	mypy --strict .

[testenv:fix]
runner = uv-venv-lock-runner
extras = quality
commands =
	ruff check --fix .
	ruff format .

[testenv:test]
runner = uv-venv-lock-runner
extras = test
commands =
	pytest -q
