[tox]
env_list = lint, type, test
min_version = 4.0
requires = tox-uv
recreate = false

[testenv]
basepython = python3.13
skip_install = true
pass_env =
	SECRET_KEY

[testenv:fix]
commands =
	ruff check --fix .
	ruff format .

[testenv:lint]
commands =
	ruff check .
	ruff format --check .

[testenv:type]
allowlist_externals = pip
commands =
	mypy --strict . -i

[testenv:test]
commands =
	pytest -q

[testenv:coverage]
commands =
	pytest --cov
