[tox]
env_list = lint, test
min_version = 4.0
requires = tox-uv

[testenv]
basepython = python3.13

[testenv:check]
extras = quality
commands =
	ruff check .
	ruff format --check .
	mypy --strict .

[testenv:fix]
extras = quality
commands =
	ruff check --fix .
	ruff format .

[testenv:lint]
extras = quality
commands =
	ruff check .
	ruff format --check .

[testenv:test]
extras = test
commands =
	pytest -q

[testenv:coverage]
extras = test
commands =
	pytest --cov
