"""Initial core models

Revision ID: 931436940d71
Revises:
Create Date: 2025-07-07 15:55:33.584736

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "931436940d71"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
