"""Rename link tables to remove _link suffix

Revision ID: 98a3d5a24453
Revises: 5750a99b38f5
Create Date: 2025-09-13 17:36:25.735914

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98a3d5a24453"
down_revision: Union[str, Sequence[str], None] = "5750a99b38f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Use batch_alter_table for SQLite compatibility when adding constraints
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_invitation_tutor_id", ["tutor_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Also use batch_alter_table for the downgrade operation
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_invitation_tutor_id", type_="unique")

    # ### end Alembic commands ###
