"""Refactor invitation model to simplified tutor token

Revision ID: c704c0199d6c
Revises: 98a3d5a24453
Create Date: 2025-09-29 15:08:53.704322

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c704c0199d6c"
down_revision: Union[str, Sequence[str], None] = "98a3d5a24453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitation_members")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("student_email", sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_invitations_token"))
        batch_op.drop_constraint(batch_op.f("uq_invitation_tutor_id"), type_="unique")
        batch_op.drop_column("id")
        batch_op.drop_column("token")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("tutors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token", sa.String(), nullable=False))
        batch_op.create_index(batch_op.f("ix_tutors_token"), ["token"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tutors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tutors_token"))
        batch_op.drop_column("token")

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("token", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("id", sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint(
            batch_op.f("uq_invitation_tutor_id"), ["tutor_id"]
        )
        batch_op.create_index(batch_op.f("ix_invitations_token"), ["token"], unique=1)
        batch_op.drop_column("student_email")

    op.create_table(
        "invitation_members",
        sa.Column("invitation_id", sa.INTEGER(), nullable=False),
        sa.Column("student_email", sa.VARCHAR(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
        ),
        sa.PrimaryKeyConstraint("invitation_id", "student_email"),
    )
    # ### end Alembic commands ###
