from typing import TYPE_CHECKING, Optional, Protocol, runtime_checkable

if TYPE_CHECKING:
    from src.rag.domain.models import Chunk, Document


@runtime_checkable
class ChunkRepositoryProtocol(Protocol):
    """Defines the contract for the chunk data repository."""

    def create_chunk(self, content_hash: str, content: str) -> "Chunk": ...
    def get_chunk_by_hash(self, content_hash: str) -> Optional["Chunk"]: ...
    def get_existing_chunks_by_hashes(self, content_hashes: list[str]) -> set[str]: ...
    def get_many_chunks_by_document(self, document: "Document") -> list["Chunk"]: ...
    def get_orphaned_chunks(self, document: "Document") -> list["Chunk"]: ...
    def delete_chunks(self, chunks: list["Chunk"]) -> None: ...
